version: '3.9'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    volumes:
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
      - ./mongo/mongo-volume:/data/db
    environment: 
      MONGO_INITDB_DATABASE: thestuffer
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    depends_on:
      - mongo
      - auth-backend
      - thestuffer-backend
      - thestuffer-frontend
    volumes:
      - ./nginx/nginx-internal.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  auth-backend:
    container_name: auth-backend
    image: auth-backend.dev
    build: ./auth-backend
    build: 
      context: ./auth-backend
      dockerfile: Dockerfile.dev
    # volumes:
    #   - type: bind
    #     source: ./app
    #     target: /app
    environment:
      MONGO_URI: mongodb://mongo:27017/thestuffer
      AUTH_MONGO_USERNAME: auth
      AUTH_MONGO_PASSWORD: 123
    depends_on:
      - mongo
    ports:
      - 3002:3002

  thestuffer-backend:
    container_name: thestuffer-backend
    image: thestuffer-backend.dev
    build: 
      context: ./thestuffer-backend
      dockerfile: Dockerfile.dev
    # volumes:
    #   - type: bind
    #     source: ./app
    #     target: /app
    environment:
      MONGO_URI: mongobd://mongo:27017/thestuffer
      STUFF_MONGO_USERNAME: stuff
      STUFF_MONGO_PASSWORD: 123
    depends_on:
      - mongo
    ports:
      - 3001:3001

  thestuffer-frontend:
    container_name: thestuffer-frontend
    image: thestuffer-frontend.dev
    build: 
      context: ./thestuffer-frontend
      dockerfile: Dockerfile.dev
    # volumes:
    #   - type: bind
    #     source: ./app
    #     target: /app
    depends_on:
      - mongo
    ports:
      - 3000:3000