version: '3.9'
services:
  mongo:
    image: ${REGISTRY_URL}/thestuffer-mongo:${VERSION}
    container_name: mongo
    volumes:
      - ./mongo/mongo-volume:/data/db
    environment: 
      MONGO_INITDB_DATABASE: thestuffer
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # ports:
    #   - 27017:27017

  reverse-proxy:
    image: ${REGISTRY_URL}/thestuffer-nginx:${VERSION}
    container_name: reverse-proxy
    depends_on:
      - mongo
      - auth-backend
      - thestuffer-backend
      - thestuffer-frontend
    ports:
      - 8080:80

  auth-backend:
    image: ${REGISTRY_URL}/auth-backend:${VERSION}
    container_name: auth-backend
    environment:
      PORT: 3002
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/thestuffer
      AUTH_MONGO_USERNAME: auth
      AUTH_MONGO_PASSWORD: 123
    depends_on:
      - mongo

  thestuffer-backend:
    container_name: thestuffer-backend
    image: ${REGISTRY_URL}/thestuffer-backend:${VERSION}
    environment:
      PORT: 3001
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/thestuffer
      STUFF_MONGO_USERNAME: stuff
      STUFF_MONGO_PASSWORD: 123
    depends_on:
      - mongo

  thestuffer-frontend:
    container_name: thestuffer-frontend
    image: ${REGISTRY_URL}/thestuffer-frontend:${VERSION}
    environment:
      PORT: 8080
    depends_on:
      - mongo
