version: '3.9'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
      - ./mongo/mongo-volume:/data/db
    ports:
      - 27017:27017
    
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on: 
      - mongo
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081