version: "3.9"
services: 
#  stuff:
#    build: ./stuff-container
#    container_name: stuff
#    depends_on: 
#      - mongo
#    ports:
#      - 3000:3000
#    environment:
#      HOST: stuff
#      PORT: 3000
#      MONGO_HOST: mongo
#      MONGO_DATABASE: ${MONGO_DATABASE}

  mongo:
    image: mongo:4.4.4
    container_name: mongo
    environment: 
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes: 
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
      - ./mongo/mongo-volume:/data/db
    ports: 
      - 27017:27017