version: "3.9"
services: 
  #the-stuffer:
  #  build: ./the-stuffer
  #  ports:
  #    - 3000:3000
  #  environment:
  #    MONGO_URL: http://main:27017
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #  networks: 
  #    - main

  mongo:
    image: mongo:4.4.4
    container_name: mongo-thestuffer
    environment: 
      MONGO_INITDB_DATABASE: thestuffer
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes: 
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
      - ./mongo/mongo-volume:/data/db
    ports: 
      - 27017-27019:27017-27019