version: "3.9"
services: 
  #the-stuffer:
  #  build: ./the-stuffer
  #  ports:
  #    - 3000:3000
  #  environment:
  #    MONGO_URL: http://main:27017
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #  networks: 
  #    - main

  mongo:
    image: mongo
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
networks: 
  main: