version: '3.9'
services:
  mongo:
    image: thestuffer-mongo
    build: ./mongo
    container_name: thestuffer-mongo
    volumes:
      - ./mongo/mongo-volume:/data/db
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
    environment: 
      MONGO_INITDB_DATABASE: thestuffer
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  auth-backend:
    container_name: auth-backend
    image: auth-backend
    build: ./auth-backend
    environment:
      PORT: 3002
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/thestuffer
      AUTH_MONGO_USERNAME: auth
      AUTH_MONGO_PASSWORD: $AUTH_MONGO_PASSWORD
      EMAIL: $EMAIL
      EMAIL_PWD: $EMAIL_PWD
    depends_on:
      - mongo

  thestuffer-backend:
    container_name: thestuffer-backend
    image: thestuffer-backend
    build: ./thestuffer-backend
    environment:
      PORT: 3001
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/thestuffer
      STUFF_MONGO_USERNAME: stuff
      STUFF_MONGO_PASSWORD: $STUFF_MONGO_PASSWORD
    depends_on:
      - mongo

  thestuffer-frontend:
    container_name: thestuffer-frontend
    image: thestuffer-frontend
    build: ./thestuffer-frontend
    depends_on:
      - mongo
    ports:
      - 8080:8080
