version: '3.9'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    env_file: .env
    volumes:
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
      - ./mongo/mongo-volume:/data/db
    ports:
      - 27017:27017

  auth:
    build: ./auth
    container_name: auth
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
    ports:
      - 3002:3002

  stuff:
    build: ./stuff
    container_name: stuff
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
    ports:
      - 3001:3001

  thestuffer:
    build: ./thestuffer
    container_name: thestuffer
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
    ports:
      - 3000:3000
