version: '3.9'
services:
  # mongo:
  #   image: mongo:4.4.4
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_DATABASE: $MONGO_DATABASE
  #     MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
  #     MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
  #   env_file: .env
  #   volumes:
  #     - ./mongo/init-scripts:/docker-entrypoint-initdb.d:ro
  #     - ./mongo/mongo-volume:/data/db
  #   ports:
  #     - 27017:27017

  auth-backend:
    image: auth-backend
    build: ./auth-backend
    container_name: auth-backend
    environment:
      THESTUFFER_HOST: thestuffer-frontend
    # depends_on:
    #   - mongo
    ports:
      - 3002:3002

  thestuffer-backend:
    image: thestuffer-backend
    build: ./thestuffer-backend
    container_name: thestuffer-backend
    environment:
      THESTUFFER_HOST: thestuffer-frontend
    # depends_on:
    #   - mongo
    ports:
      - 3001:3001

  thestuffer-frontend:
    image: thestuffer-frontend
    build: ./thestuffer-frontend
    container_name: thestuffer-frontend
    environment:
      REACT_APP_STUFF_HOST: thestuffer-backend
      REACT_APP_AUTH_HOST: auth-backend
    # depends_on:
    #   - mongo
    ports:
      - 8080:8080
