POST http://localhost:9000/stuff/throwing/create
Content-Type: application/json

{
    "landing_id": "azerty",
    "movement": "throw",
    "position": {
        "lat": 0,
        "lng": 0,
        "floor": 0
    },
    "video": {
        "id": "Gu064JTzQu8",
        "time": 100
    },
    "tickrate": {
        "64": true,
        "128": true
    },
    "description": "perfect smoke"
}
###
DELETE  http://localhost:9000/stuff/throwing/delete/606b5ecc74b86f27b4f59e16
###
PUT http://localhost:9000/stuff/throwing/update/60606de708fc3a3e006f7f94
Content-Type: application/json

{
    "description": "1",
    "reaction": {
        "hyped": true,
        "user": "azerty",
        "hidden": false
    }
}
###
POST http://localhost:9000/stuff/throwing/search
Content-Type: application/json

{
    "landing_id": "azerty",
    "tickrate": {
        "64": true,
        "128": true
    }
}

###
GET http://localhost:9000/stuff/throwing/get/606b5ecc74b86f27b4f59e16