POST http://localhost:3001/stuff/create
Content-Type: application/json

{
    "collection": "landing",
    "type": "smoke",
    "map": "inferno",
    "position": {
        "lat": 0,
        "lng": 0,
        "floor": 0
    }
}
###
DELETE  http://localhost:3001/stuff/landing/delete/6060fb4ccced86316c3a866c
###
PUT http://localhost:3001/stuff/landing/update/6060fb4ccced86316c3a866c
Content-Type: application/json

{
    "map": "inferno"
}
###
POST http://localhost:3001/stuff/search
Content-Type: application/json

{
    "collection": "throwing",
    "map": "de_mirage",
    "position": {
        "floor": 0
    }
}

###
GET http://localhost:3001/stuff/landing/get/6060fb4ccced86316c3a866c