POST http://localhost:9000/stuff/throwing/create
Content-Type: application/json

{
    "hit_id": "azerty",
    "position": {
        "lat": 0,
        "lng": 0,
        "floor": 0
    },
    "type": "throw",
    "video": {
        "id": "Gu064JTzQu8",
        "time": 100
    },
    "tickrate": {
        "64": true,
        "128": true
    },
    "description": "perfect smoke"
}