PUT http://localhost:9000/stuff/throwing/update/605f7217f25b9e3e488c879b
Content-Type: application/json

{
    "description": "slt",
    "new_reaction": {
        "hyped": true,
        "user": "azerty",
        "hidden": false
    }
}