PUT http://localhost:9000/stuff/throwing/update/60606de708fc3a3e006f7f94
Content-Type: application/json

{
    "description": "slt",
    "new_reaction": {
        "hyped": true,
        "user": "azerty",
        "hidden": false
    }
}