apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend-deployment
  labels:
    app: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: auth-backend
          image: 457436777387.dkr.ecr.eu-west-1.amazonaws.com/auth-backend:latest
          ports:
            - containerPort: 3002
          env:
            - name: AUTH_PORT
              value: '3002'
            - name: THESTUFFER_HOST
              value: thestuffer-frontend
            - name: THESTUFFER_PORT
              value: '3000'
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: uri
            - name: AUTH_MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-secret
                  key: username
            - name: AUTH_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-secret
                  key: password
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens-secret
                  key: access-token
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens-secret
                  key: refresh-token
---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
spec:
  selector:
    app: auth-backend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
