apiVersion: apps/v1
kind: Deployment
metadata:
  name: thestuffer-backend-deployment
  labels:
    app: thestuffer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thestuffer-backend
  template:
    metadata:
      labels:
        app: thestuffer-backend
    spec:
      containers:
      - name: thestuffer-backend
        image: 
        ports: 457436777387.dkr.ecr.eu-west-1.amazonaws.com/thestuffer-backend:latest
        - containerPort: 3001
