apiVersion: apps/v1
kind: Deployment
metadata:
  name: thestuffer-frontend-deployment
  labels:
    app: thestuffer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thestuffer-frontend
  template:
    metadata:
      labels:
        app: thestuffer-frontend
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: thestuffer-backend
          image: 457436777387.dkr.ecr.eu-west-1.amazonaws.com/thestuffer-frontend:1c5e1505a75fcc7cfdaf96641690ace8e3f69f56
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thestuffer-frontend-service
spec:
  selector:
    app: thestuffer-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
