apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: the-stuffer
  name: thestuffer-backend-deployment
  labels:
    app: thestuffer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thestuffer-backend
  template:
    metadata:
      labels:
        app: thestuffer-backend
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: thestuffer-backend
          image: 457436777387.dkr.ecr.eu-west-3.amazonaws.com/thestuffer-backend:f2321169fb620780cc48047b9b21565e9312bab7
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3001'
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: uri
            - name: STUFF_MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stuff-mongo-secret
                  key: username
            - name: STUFF_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stuff-mongo-secret
                  key: password
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens-secret
                  key: access-token
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens-secret
                  key: refresh-token
---
apiVersion: v1
kind: Service
metadata:
  namespace: the-stuffer
  name: thestuffer-backend-service
spec:
  selector:
    app: thestuffer-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
