apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: the-stuffer
  name: thestuffer-frontend-deployment
  labels:
    app: thestuffer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thestuffer-frontend
  template:
    metadata:
      labels:
        app: thestuffer-frontend
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: thestuffer-backend
          image: 457436777387.dkr.ecr.eu-west-3.amazonaws.com/thestuffer-frontend:f2321169fb620780cc48047b9b21565e9312bab7
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: the-stuffer
  name: thestuffer-frontend-service
spec:
  selector:
    app: thestuffer-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
