name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  image:
    name: Image storage on registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        uses: docker/login-action@v1.9.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ secrets.REGISTRY_URL }}
          # Username used to log against the Docker registry
          username: ${{ secrets.REGISTRY_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build images
        run: |
          docker build --tag ${{ secrets.REGISTRY_URL }}/auth-backend:${{ github.sha }} ./auth-backend
          docker build --tag ${{ secrets.REGISTRY_URL }}/thestuffer-backend:${{ github.sha }} ./thestuffer-backend
          docker build --tag ${{ secrets.REGISTRY_URL }}/thestuffer-frontend:${{ github.sha }} ./thestuffer-frontend
          docker build --tag ${{ secrets.REGISTRY_URL }}/thestuffer-mongo:${{ github.sha }} ./mongo

      - name: Push images
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/auth-backend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URL }}/thestuffer-backend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URL }}/thestuffer-frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URL }}/thestuffer-mongo:${{ github.sha }}

      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Thestuffer deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SSH_USER }}/workspace/thestuffer/ && cd "$_"

            docker-compose -f deployment.yml down
            rm deployment.yml .env

            git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/felixcapuano/the-stuffer
            cp ./the-stuffer/dist/deployment.yml ./deployment.yml
            rm -r ./the-stuffer/

            touch .env
            echo "VERSION=${{ github.sha }}" >> .env
            echo "${{ secrets.THESTUFFER }}" >> .env

            docker login --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_URL }}
            docker-compose -f deployment.yml up --build -d
